# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: osx_image: xcode11.6
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# xcode_project: Example/SwiftyFontIcon.xcworkspace
# xcode_scheme: MyNewProjectTests
# xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftyFontIcon.xcworkspace -scheme SwiftyFontIcon-Example -sdk iphonesimulator13.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
