# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

# osx_image: xcode11.6
# language: swift
# # cache: cocoapods
# # podfile: Example/Podfile
# # before_install:
# # - gem install cocoapods # Since Travis is not always on latest version
# # - pod install --project-directory=Example
# xcode_workspace: Example/SwiftyFontIcon.xcworkspace
# xcode_scheme: SwiftyFontIcon-Example
# xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 8
# # script:
# # - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftyFontIcon.xcworkspace -scheme SwiftyFontIcon-Example -sdk iphonesimulator13.6 ONLY_ACTIVE_ARCH=NO | xcpretty
# # - pod lib lint


os: osx
osx_image: xcode11.6
language: swift

branches:
  only:
    - develop
stages:
  - name: lint
    # if: NOT branch =~ ^\d+\.\d+\.\d+$
  - name: test
    # if: type != push OR branch =~ /^\d+\.\d+\.\d+$/
  - name: deploy
    # if: branch =~ ^\d+\.\d+\.\d+$
jobs:
  include:
   
    - &pod
      stage: lint
      cache: cocoapods
      install: gem install cocoapods -v '~> 1.7.0'
      script: pod lib lint --allow-warnings --fail-fast --swift-version=$SWIFT
      osx_image: xcode11.6
      env: SWIFT=5.0

    - &test
      stage: test
      name: macOS / Xcode 10.2
      xcode_workspace: Example/SwiftyFontIcon.xcworkspace
      xcode_scheme: SwiftyFontIcon-Example
      xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 8
      # after_success: bash <(curl -s https://codecov.io/bash)

    - name: '`pod trunk push`'
      stage: deploy
      install: gem install cocoapods -v '~> 1.7.0'
      script: |
        set -exo pipefail
        pod trunk push --verbose --allow-warnings | tee pod.log | ruby -e 'ARGF.each{ print "." }'
      # ^^ pipe because Travis times us out if there is no output
      # AND `pod` defaults to hardly any output
      # BUT `--verbose` generates so much output that Travis kills our script due to *too much* output!
      # --allow-warnings because Bolts generates warnings and CocoaPods fails you even if your deps emit warnings
      after_failure: cat pod.log | grep error